# Coefficients and Covariance Matrix

In [1]:
import tprstats
import pandas as pd
import numpy as np
coffee_data = pd.read_excel('../data/Coffee_Data.xlsx', engine='openpyxl')
diamonds_211 = pd.read_excel('../data/Diamonds_211.xlsx', engine='openpyxl')

In [2]:
model_coffee_ts = tprstats.model(name = "ts", formula='cons~rpcarb+rpcinc+rpcofe', data=coffee_data)

In [3]:
coefs, cov_matrix = model_coffee_ts.get_coefficients_and_covariance()

                 coefs  Intercept    rpcarb    rpcinc    rpcofe
0  Intercept  0.057574   2.882735 -0.011149 -0.048890 -0.005034
1     rpcarb  0.090120  -0.011149  0.000049  0.000197  0.000012
2     rpcinc  0.123477  -0.048890  0.000197  0.000885  0.000062
3     rpcofe -0.012582  -0.005034  0.000012  0.000062  0.000024


In [4]:
rng = np.random.default_rng()
rng.multivariate_normal(coefs, cov_matrix)

array([-3.21589218,  0.10698517,  0.19529052, -0.01608342])

In [5]:
observations = rng.multivariate_normal(coefs, cov_matrix, 1000000)
df = pd.DataFrame(observations)

In [6]:
print(observations)

[[ 3.69674014e+00  7.53247745e-02  6.35322671e-02 -1.88091634e-02]
 [-1.85589805e+00  9.71912992e-02  1.49288457e-01 -7.36916732e-03]
 [-2.15604577e-02  9.33711081e-02  1.24204990e-01 -1.50329338e-02]
 ...
 [ 2.64180156e+00  8.23955322e-02  8.28062135e-02 -1.88145446e-02]
 [ 3.36388532e-01  8.60685979e-02  1.10490247e-01 -6.96721959e-03]
 [-2.15699060e+00  9.50459985e-02  1.56408801e-01 -3.14704822e-03]]


In [ ]:
print(df)

               0         1         2         3
0       3.696740  0.075325  0.063532 -0.018809
1      -1.855898  0.097191  0.149288 -0.007369
2      -0.021560  0.093371  0.124205 -0.015033
3       1.292850  0.086688  0.106415 -0.017610
4      -0.013957  0.088730  0.116880 -0.007937
...          ...       ...       ...       ...
999995  0.261648  0.084980  0.122833 -0.008981
999996  3.687927  0.076488  0.056434 -0.017738
999997  2.641802  0.082396  0.082806 -0.018815
999998  0.336389  0.086069  0.110490 -0.006967
999999 -2.156991  0.095046  0.156409 -0.003147

[1000000 rows x 4 columns]


In [8]:
df.mean()

0    0.053709
1    0.090134
2    0.123547
3   -0.012574
dtype: float64