# Coefficients and Covariance Matrix

In [14]:
import tprstats
import pandas as pd
import numpy as np
coffee_data = pd.read_excel('../data/Coffee_Data.xlsx', engine='openpyxl')
diamonds_211 = pd.read_excel('../data/Diamonds_211.xlsx', engine='openpyxl')

In [15]:
model_coffee_ts = tprstats.model(name = "ts", formula='cons~rpcarb+rpcinc+rpcofe', data=coffee_data)

In [16]:
coefs, cov_matrix = model_coffee_ts.coefficients_and_covariance()

In [17]:
rng = np.random.default_rng()
rng.multivariate_normal(coefs, cov_matrix)

array([ 0.9172334 ,  0.08529847,  0.10575733, -0.01217535])

In [18]:
observations = rng.multivariate_normal(coefs, cov_matrix, 1000000)
df = pd.DataFrame(observations)

In [19]:
print(observations)

[[ 3.24422641  0.07610235  0.05937123 -0.01337342]
 [-0.29940771  0.09052016  0.11912579 -0.00842717]
 [ 0.23385433  0.08718008  0.12456651 -0.01067999]
 ...
 [-0.77803988  0.09406142  0.1485133  -0.01397473]
 [ 3.36754223  0.07933322  0.06581782 -0.02094708]
 [ 0.97176293  0.08600264  0.10671679 -0.01323439]]


In [20]:
print(df)

               0         1         2         3
0       3.244226  0.076102  0.059371 -0.013373
1      -0.299408  0.090520  0.119126 -0.008427
2       0.233854  0.087180  0.124567 -0.010680
3       0.885428  0.087474  0.111143 -0.015219
4      -2.072088  0.096889  0.158066 -0.006926
...          ...       ...       ...       ...
999995 -1.158917  0.097344  0.157117 -0.015450
999996 -2.494067  0.102218  0.166136 -0.008725
999997 -0.778040  0.094061  0.148513 -0.013975
999998  3.367542  0.079333  0.065818 -0.020947
999999  0.971763  0.086003  0.106717 -0.013234

[1000000 rows x 4 columns]


In [21]:
df.mean()

0    0.056730
1    0.090119
2    0.123474
3   -0.012571
dtype: float64

In [24]:
df=model_coffee_ts.coefficients_draw()

In [25]:
df.mean()

Intercept    0.056694
rpcarb       0.090116
rpcinc       0.123460
rpcofe      -0.012565
dtype: float64