# Coefficients and Covariance Matrix

In [1]:
import tprstats
import pandas as pd
import numpy as np
coffee_data = pd.read_excel('../data/Coffee_Data.xlsx', engine='openpyxl')
diamonds_211 = pd.read_excel('../data/Diamonds_211.xlsx', engine='openpyxl')

In [2]:
model_coffee_ts = tprstats.model(name = "ts", formula='cons~rpcarb+rpcinc+rpcofe', data=coffee_data)

In [3]:
coefs, cov_matrix = model_coffee_ts.coefficients_and_covariance()

In [4]:
rng = np.random.default_rng()
rng.multivariate_normal(coefs, cov_matrix)

array([-2.21401522,  0.09707592,  0.15896744, -0.00497443])

In [5]:
observations = rng.multivariate_normal(coefs, cov_matrix, 1000000)
df = pd.DataFrame(observations)

In [6]:
print(observations)

[[-0.83406746  0.08919348  0.12371612 -0.00467968]
 [-0.89248941  0.09261263  0.14387421 -0.0103903 ]
 [-3.97070508  0.10675129  0.19184905 -0.00678751]
 ...
 [-1.34305334  0.09368259  0.16040112 -0.01106054]
 [ 1.80772986  0.08525099  0.09622069 -0.01931936]
 [-3.1950004   0.1030692   0.17751374 -0.00941184]]


In [7]:
print(df)

               0         1         2         3
0      -0.834067  0.089193  0.123716 -0.004680
1      -0.892489  0.092613  0.143874 -0.010390
2      -3.970705  0.106751  0.191849 -0.006788
3       0.313550  0.089091  0.119028 -0.014925
4      -0.944829  0.092605  0.135269 -0.007857
...          ...       ...       ...       ...
999995  0.783261  0.085544  0.113065 -0.012032
999996 -0.118566  0.086518  0.123913 -0.006179
999997 -1.343053  0.093683  0.160401 -0.011061
999998  1.807730  0.085251  0.096221 -0.019319
999999 -3.195000  0.103069  0.177514 -0.009412

[1000000 rows x 4 columns]


In [8]:
df.mean()

0    0.056793
1    0.090123
2    0.123491
3   -0.012580
dtype: float64

In [9]:
df=model_coffee_ts.coefficients_draw()

In [10]:
df.mean()

Intercept    2.135226
rpcarb       0.084521
rpcinc       0.086733
rpcofe      -0.018034
dtype: float64