# Coefficients and Covariance Matrix

In [1]:
import tprstats
import pandas as pd
import numpy as np
coffee_data = pd.read_excel('../data/Coffee_Data.xlsx', engine='openpyxl')
diamonds_211 = pd.read_excel('../data/Diamonds_211.xlsx', engine='openpyxl')

In [2]:
model_coffee_ts = tprstats.model(name = "ts", formula='cons~rpcarb+rpcinc+rpcofe', data=coffee_data)

In [3]:
coefs, cov_matrix = model_coffee_ts.coefficients_and_covariance()

In [4]:
rng = np.random.default_rng()
rng.multivariate_normal(coefs, cov_matrix)

array([ 0.54957717,  0.08986039,  0.12990827, -0.01950158])

In [5]:
observations = rng.multivariate_normal(coefs, cov_matrix, 1000000)
df = pd.DataFrame(observations)

In [6]:
print(observations)

[[ 0.91181328  0.08972305  0.11317429 -0.0182275 ]
 [ 6.12978457  0.0702123   0.03022137 -0.03003992]
 [ 1.71776875  0.08591423  0.10033105 -0.01907534]
 ...
 [-1.44468381  0.09692077  0.15132774 -0.01149371]
 [-1.62504714  0.09876438  0.15592442 -0.01222604]
 [ 3.06729988  0.07476399  0.0629481  -0.01259341]]


In [7]:
print(df)

               0         1         2         3
0       0.911813  0.089723  0.113174 -0.018228
1       6.129785  0.070212  0.030221 -0.030040
2       1.717769  0.085914  0.100331 -0.019075
3      -1.664596  0.097694  0.162676 -0.013304
4       0.894314  0.087805  0.114655 -0.016823
...          ...       ...       ...       ...
999995  1.092510  0.091947  0.119321 -0.024859
999996 -4.070985  0.104324  0.205854 -0.007680
999997 -1.444684  0.096921  0.151328 -0.011494
999998 -1.625047  0.098764  0.155924 -0.012226
999999  3.067300  0.074764  0.062948 -0.012593

[1000000 rows x 4 columns]


In [8]:
df.mean()

0    0.055866
1    0.090121
2    0.123494
3   -0.012570
dtype: float64